name: Run Tests

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  test:
    run-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/stepsetup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip insrall -r backend/requirements.txt

      - name: Run Tests
        run: |
          pytest tests/ --disable-warnings --maxfail=1